# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 22:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Toys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Toy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='')),
                ('description', models.CharField(default='', max_length=1000)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameModel(
            old_name='CartMetalFilter',
            new_name='CartProducerFilter',
        ),
        migrations.RenameModel(
            old_name='Metal',
            new_name='Producer',
        ),
        migrations.RemoveField(
            model_name='jewel',
            name='metal',
        ),
        migrations.RenameField(
            model_name='cartfilter',
            old_name='fineness_from',
            new_name='age_from',
        ),
        migrations.RenameField(
            model_name='cartfilter',
            old_name='fineness_to',
            new_name='age_to',
        ),
        migrations.RenameField(
            model_name='cartproducerfilter',
            old_name='metal',
            new_name='producer',
        ),
        migrations.RemoveField(
            model_name='cartfilter',
            name='weight_from',
        ),
        migrations.RemoveField(
            model_name='cartfilter',
            name='weight_to',
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Toys.Toy'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Toys.Toy'),
        ),
        migrations.DeleteModel(
            name='Jewel',
        ),
        migrations.AddField(
            model_name='toy',
            name='producer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Toys.Producer'),
        ),
    ]
